---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: boney
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app-deployment
...